---
title: "Experiments"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
library(dmea02)
library(latex2exp)
library(gridExtra)
```



## Exp 1. How good is the last iteration of the MCEM

```{r, exp1}
time = proc.time()
n_sim = 100
n_trees = 10
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
for(i in 1:n_sim){
  est = sim.est(n_trees=n_trees,pars=c(0.8,0.1,40),seed=i)
  RP[i,] = est$real
  MP[i,] = est$est
}
```


```{r}
dmea::par_est_vis(P=MP,par=1,PR=RP,true=0.8)
dmea::par_est_vis(P=MP,par=2,PR=RP,true=0.1)
dmea::par_est_vis(P=MP,par=3,PR=RP,true=40)
```

```{r}
summary(MP)
summary(RP)
get.time(time)
```

### $\mu_0 = 0.2$
 
```{r, exp2}
time = proc.time()
n_sim = 1000
n_trees = 10
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
for(i in 1:n_sim){
  est = sim.est(n_trees=n_trees,pars=c(0.8,0.2,40),seed=i)
  RP[i,] = est$real
  MP[i,] = est$est
}
get.time(time)
```

```{r}
get.time(time)
dmea::par_est_vis(P=MP,par=1,PR=RP,true=0.8)
dmea::par_est_vis(P=MP,par=2,PR=RP,true=0.2)
dmea::par_est_vis(P=MP,par=3,PR=RP,true=40)
summary(MP)
summary(RP)
```

### $\mu_0 = 0.4$
 
```{r, exp4}
time = proc.time()
n_sim = 1000
n_trees = 10
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
for(i in 1:n_sim){
  est = sim.est(n_trees=n_trees,pars=c(0.8,0.4,40),seed=i)
  RP[i,] = est$real
  MP[i,] = est$est
}
get.time(time)
```


```{r}
get.time(time)
dmea::par_est_vis(P=MP,par=1,PR=RP,true=0.8)
dmea::par_est_vis(P=MP,par=2,PR=RP,true=0.4)
dmea::par_est_vis(P=MP,par=3,PR=RP,true=40)
summary(MP)
summary(RP)
```

### more trees

```{r, exp10}
time = proc.time()
n_sim = 1000
n_trees = 100
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
for(i in 1:n_sim){
  est = sim.est(n_trees=n_trees,pars=c(0.8,0.1,40),seed=i)
  RP[i,] = est$real
  MP[i,] = est$est
}
print(proc.time()-p)
get.time(time)
```


```{r}
dmea::par_est_vis(P=MP,par=1,PR=RP,true=0.8)
dmea::par_est_vis(P=MP,par=2,PR=RP,true=0.1)
dmea::par_est_vis(P=MP,par=3,PR=RP,true=40)
```

```{r}
summary(MP)
summary(RP)
```


### more trees 

```{r, exp40,eval=F}
time = proc.time()
n_sim = 1000
n_trees = 100
MP = matrix(nrow=n_sim,ncol=3)
RP = matrix(nrow=n_sim,ncol=3)
p = proc.time()
for(i in 1:n_sim){
  est = sim.est(n_trees=n_trees,pars=c(0.8,0.4,40),seed=i)
  RP[i,] = est$real
  MP[i,] = est$est
}
get.time(time)
```


```{r}
get.time(time)
dmea::par_est_vis(P=MP,par=1,PR=RP)
dmea::par_est_vis(P=MP,par=2,PR=RP)
dmea::par_est_vis(P=MP,par=3,PR=RP)
```

```{r}
get.time(time)
summary(MP)
summary(RP)
```
